# Generated by Django 2.1.4 on 2019-01-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190109_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(blank=True, null=True)),
                ('subreddit', models.TextField(blank=True, null=True)),
                ('scan_type', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='scan_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subreddit',
        ),
    ]
