# Generated by Django 2.1.4 on 2019-01-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190109_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='subreddit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
