# Generated by Django 2.1.4 on 2019-01-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190109_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='input',
            name='keyword',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='scan_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='input',
            name='subreddit',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
