# Generated by Django 2.1.4 on 2019-01-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190109_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='alert_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'SMS')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='input',
            name='keyword',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='subreddit',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
