# Generated by Django 2.1.4 on 2019-01-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190111_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='alert',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
