# Generated by Django 2.1.4 on 2019-01-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_input_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='input',
            name='alert_type',
        ),
        migrations.AddField(
            model_name='input',
            name='enter_email_or_phone_number',
            field=models.CharField(help_text='Phone numbers have to be in +1XXXXXXXXXX format', max_length=80, null=True),
        ),
    ]
