# Generated by Django 2.1.4 on 2019-01-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190111_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
